{% set name = "ytmdl" %}
{% set version = "2022.3.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ytmdl-{{ version }}.tar.gz
  sha256: da510e8304a2e1f0152be8095ef8d640305621bd5c383166522ab41547e9c970
  patches:
    - setup.py.patch

build:
  entry_points:
    - ytmdl = ytmdl:entry
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - bs4
    - colorama
    - downloader-cli
    - ffmpeg-python
    - itunespy
    - musicbrainzngs
    - mutagen
    - pip
    - pydes
    - pysocks
    - python >=3.6
    - pyxdg
    - requests
    - rich
    - simber
    - spotipy
    - unidecode
    - urllib3
    - youtube-search-python
    - yt-dlp
    - ytmusicapi
    - beautifulsoup4
  run:
    - bs4
    - colorama
    - downloader-cli
    - ffmpeg-python
    - itunespy
    - musicbrainzngs
    - mutagen
    - pydes
    - pysocks
    - python >=3.6
    - pyxdg
    - requests
    - rich
    - simber
    - spotipy
    - unidecode
    - urllib3
    - yt-dlp >=2022.03.08.1
    - youtube-search-python
    - ytmusicapi
    - beautifulsoup4

test:
  imports:
    - ytmdl
    - ytmdl.meta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepjyoti30/ytmdl
  dev_url: https://github.com/deepjyoti30/ytmdl
  summary: Youtube Music Downloader
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
