{% set name = "ytmdl" %}
{% set version = "2023.11.26" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ytmdl-{{ version }}.tar.gz
  sha256: 226deb400b3f4d8a2892fe85786a54ead27150604c6fafd45b564c0e0f455b8b

build:
  entry_points:
    - ytmdl = ytmdl:entry
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - yt-dlp >=2022.7.6
    - mutagen
    - itunespy
    - requests
    - colorama
    - beautifulsoup4
    - downloader-cli >=0.3.4
    - pyxdg
    - ffmpeg-python
    - pysocks
    - unidecode
    - youtube-search-python
    - pydes
    - urllib3
    - simber ==0.2.6
    - rich
    - musicbrainzngs
    - ytmusicapi
    - spotipy
    - pip
  run:
    - python >=3.6
    - yt-dlp >=2022.7.6
    - mutagen
    - itunespy
    - requests
    - colorama
    - beautifulsoup4
    - downloader-cli >=0.3.4
    - pyxdg
    - ffmpeg-python
    - pysocks
    - unidecode
    - youtube-search-python
    - pydes
    - urllib3
    - simber ==0.2.6
    - rich
    - musicbrainzngs
    - ytmusicapi
    - spotipy

test:
  imports:
    - ytmdl
    - ytmdl.meta
  commands:
    - pip check
    - ytmdl --help
  requires:
    - pip

about:
  home: https://github.com/deepjyoti30/ytmdl
  dev_url: https://github.com/deepjyoti30/ytmdl
  summary: Youtube Music Downloader
  license: MIT
  license_file: LICENSE
  description: Download songs from YouTube by getting the audio from YouTube and the metadata from sources like Itunes, Spotify, Gaana etc.

extra:
  recipe-maintainers:
    - HeavyTony2
